#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN_BASE_PATH="$PLUGIN_PATH"
if [[ -n $DOKKU_API_VERSION ]]; then
  PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi
source "$PLUGIN_BASE_PATH/common/functions"

get_telegram_root() {
  if [[ -d "$DOKKU_ROOT/$1" ]]; then
    verify_app_name "$1"
    APP="$1"
    echo "$DOKKU_ROOT/$APP"
  else
    echo "$DOKKU_ROOT"
  fi
}

get_token() {
  if [[ -n $1 && -n $2 ]]; then
    echo "$2"
  else
    echo "$1"
  fi
}

get_chat_id() {
  if [[ -n $1 && -n $2 ]]; then
    echo "$2"
  else
    echo "$1"
  fi
}

case "$1" in
  telegram:set_token)
    TELEGRAM_ROOT=$(get_telegram_root "$2")
    TOKEN=$(get_token "$2" "$3")
    [[ -z $TOKEN ]] && echo "Please specify a token" && exit 1
    echo "$TOKEN" > "$TELEGRAM_ROOT/TELEGRAM_TOKEN"
    ;;

  telegram:set_chat_id)
    TELEGRAM_ROOT=$(get_telegram_root "$2")
    CHAT_ID=$(get_chat_id "$2" "$3")
    [[ -z $CHAT_ID ]] && echo "Please specify a chat ID" && exit 1
    echo "$CHAT_ID" > "$TELEGRAM_ROOT/TELEGRAM_CHAT_ID"
    ;;

  telegram:clear_token)
    TELEGRAM_ROOT=$(get_telegram_root "$2")
    rm "$TELEGRAM_ROOT/TELEGRAM_TOKEN"
    ;;

  telegram:get)
    TELEGRAM_ROOT=$(get_telegram_root "$2")
    cat "$TELEGRAM_ROOT/TELEGRAM_TOKEN"
    cat "$TELEGRAM_ROOT/TELEGRAM_CHAT_ID"
    ;;

  help)
    HELP=$(cat<<EOF
    telegram:set_token [app] <token>, Set Telegram BotAPI token
    telegram:set_chat_id [app] <chat_id>, Set chat ID
    telegram:clear_token [app], Clears Telegram token
    telegram:clear_chat_id [app], Clears Telegram token
    telegram:get [app], Display Telegram data
EOF
)
    if [[ -n $DOKKU_API_VERSION ]]; then
      echo "$HELP"
    else
      cat && echo "$HELP"
    fi
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;
esac
