#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="$2"
HOSTNAME=$(hostname -f)
TELEGRAM_API="https://api.telegram.org/bot"
TELEGRAM_ENDPOINT="/sendMessage"

if [[ -f "$DOKKU_ROOT/$APP/TELEGRAM_TOKEN" || -f "$DOKKU_ROOT/TELEGRAM_TOKEN" ]]; then
  if [[ -f "$DOKKU_ROOT/$APP/TELEGRAM_CHAT_ID" || -f "$DOKKU_ROOT/TELEGRAM_CHAT_ID" ]]; then
    echo "-----> Notifying Telegram chat ..."
    URL=$(dokku url $APP)
    TOKEN=$(cat "$DOKKU_ROOT/$APP/TELEGRAM_TOKEN" 2> /dev/null || cat "$DOKKU_ROOT/TELEGRAM_TOKEN" 2> /dev/null)
    CHAT_ID=$(cat "$DOKKU_ROOT/$APP/TELEGRAM_CHAT_ID" 2> /dev/null || cat "$DOKKU_ROOT/TELEGRAM_CHAT_ID" 2> /dev/null)
    TELEGRAM_URL="${TELEGRAM_API}${TELEGRAM_TOKEN}${TELEGRAM_ENDPOINT}"
    TEXT="Deployed $APP to $HOSTNAME via $URL"
    RESULT=$(curl -X POST "${TELEGRAM_URL}" -w "%{http_code}" -F chat_id="${TELEGRAM_CHAT_ID}" -F text="${TEXT}")
    echo "       ${RESULT}"
  fi
fi
