#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
HOSTNAME=$(hostname -f)
TELEGRAM_API="https://api.telegram.org/bot"
TELEGRAM_ENDPOINT="/sendMessage"

echo "Trying to find token and chat_id"

if [[ -f "$DOKKU_ROOT/TELEGRAM_TOKEN" ]]; then
  if [[ -f "$DOKKU_ROOT/TELEGRAM_CHAT_ID" ]]; then
    echo "-----> Notifying Telegram chat ..."
    URL=$(dokku urls $APP|tail -n1)
    TOKEN=$(cat "$DOKKU_ROOT/TELEGRAM_TOKEN" 2> /dev/null)
    CHAT_ID=$(cat "$DOKKU_ROOT/TELEGRAM_CHAT_ID" 2> /dev/null)
    TEXT="Created $APP on $HOSTNAME via $URL"
    RESULT=$(curl -X POST "${TELEGRAM_API}${TOKEN}${TELEGRAM_ENDPOINT}" -w "%{http_code}" -F chat_id="${CHAT_ID}" -F text="${TEXT}")
    echo "${RESULT}"
  fi
fi
